//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Demo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates and numbers are formatted according to the selected language:.
        /// </summary>
        internal static string Label_Bindings_Date {
            get {
                return ResourceManager.GetString("Label_Bindings_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callback:.
        /// </summary>
        internal static string Label_CodeBehind_Callback {
            get {
                return ResourceManager.GetString("Label_CodeBehind_Callback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatted value:.
        /// </summary>
        internal static string Label_CodeBehind_Format {
            get {
                return ResourceManager.GetString("Label_CodeBehind_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value from resources:.
        /// </summary>
        internal static string Label_CodeBehind_Resource {
            get {
                return ResourceManager.GetString("Label_CodeBehind_Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format string from resources:.
        /// </summary>
        internal static string Label_CodeBehind_ResourceFormat {
            get {
                return ResourceManager.GetString("Label_CodeBehind_ResourceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag:.
        /// </summary>
        internal static string Label_Flag {
            get {
                return ResourceManager.GetString("Label_Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string Label_Language {
            get {
                return ResourceManager.GetString("Label_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language (this panel only):.
        /// </summary>
        internal static string Label_Multilingual_Language {
            get {
                return ResourceManager.GetString("Label_Multilingual_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non UI thread:.
        /// </summary>
        internal static string Label_Multithreading_NonUIThread {
            get {
                return ResourceManager.GetString("Label_Multithreading_NonUIThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected language:.
        /// </summary>
        internal static string Label_SelectedLanguage {
            get {
                return ResourceManager.GetString("Label_SelectedLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default (English (US)).
        /// </summary>
        internal static string LanguageName {
            get {
                return ResourceManager.GetString("LanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a template in style..
        /// </summary>
        internal static string Text_ComplexTemplate {
            get {
                return ResourceManager.GetString("Text_ComplexTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current .NET culture is: {0}..
        /// </summary>
        internal static string Text_CurrentCulture {
            get {
                return ResourceManager.GetString("Text_CurrentCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The callback has been called {0} times..
        /// </summary>
        internal static string Text_LanguageChanges {
            get {
                return ResourceManager.GetString("Text_LanguageChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current time is: {0}..
        /// </summary>
        internal static string Text_Multithreading_CurrentTime {
            get {
                return ResourceManager.GetString("Text_Multithreading_CurrentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-dependency properties can be localized in XAML and code-behind..
        /// </summary>
        internal static string Text_NonDependencyProperty {
            get {
                return ResourceManager.GetString("Text_NonDependencyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an inline template..
        /// </summary>
        internal static string Text_SimpleTemplate {
            get {
                return ResourceManager.GetString("Text_SimpleTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This text can have different color, font, size and margin..
        /// </summary>
        internal static string Text_StyleMessage {
            get {
                return ResourceManager.GetString("Text_StyleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bindings.
        /// </summary>
        internal static string Title_Bindings {
            get {
                return ResourceManager.GetString("Title_Bindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code-behind localization.
        /// </summary>
        internal static string Title_CodeBehind {
            get {
                return ResourceManager.GetString("Title_CodeBehind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple languages.
        /// </summary>
        internal static string Title_Multilingual {
            get {
                return ResourceManager.GetString("Title_Multilingual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple threads.
        /// </summary>
        internal static string Title_Multithreading {
            get {
                return ResourceManager.GetString("Title_Multithreading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Resource Files.
        /// </summary>
        internal static string Title_ResourceFiles {
            get {
                return ResourceManager.GetString("Title_ResourceFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles.
        /// </summary>
        internal static string Title_Style {
            get {
                return ResourceManager.GetString("Title_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-dependency properties and templates.
        /// </summary>
        internal static string Title_Templates {
            get {
                return ResourceManager.GetString("Title_Templates", resourceCulture);
            }
        }
    }
}
